# Generated by Django 4.2.4 on 2024-01-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.CharField(default='https://res.cloudinary.com/dhrxjuluu/image/upload/v1704501875/k33tkcn30yjax1og7scw.png', max_length=100),
        ),
    ]
