# Generated by Django 4.2.4 on 2024-01-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
