# Generated by Django 4.2.4 on 2024-01-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productreview_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
